/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AXZ
 */
public class Kasir extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Harga = new javax.swing.JLabel();
        Banyak = new javax.swing.JLabel();
        Diskon = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Judul = new javax.swing.JLabel();
        Input1 = new javax.swing.JTextField();
        Input2 = new javax.swing.JTextField();
        Input3 = new javax.swing.JTextField();
        Input4 = new javax.swing.JTextField();
        Input5 = new javax.swing.JTextField();
        Input6 = new javax.swing.JTextField();
        Input7 = new javax.swing.JTextField();
        Input8 = new javax.swing.JTextField();
        Input9 = new javax.swing.JTextField();
        Input10 = new javax.swing.JTextField();
        Input11 = new javax.swing.JTextField();
        Input12 = new javax.swing.JTextField();
        Harga1 = new javax.swing.JLabel();
        Harga2 = new javax.swing.JLabel();
        Harga3 = new javax.swing.JLabel();
        Diskon1 = new javax.swing.JLabel();
        Diskon2 = new javax.swing.JLabel();
        Diskon3 = new javax.swing.JLabel();
        Diskon4 = new javax.swing.JLabel();
        Diskon5 = new javax.swing.JLabel();
        Diskon6 = new javax.swing.JLabel();
        Input13 = new javax.swing.JTextField();
        Input14 = new javax.swing.JTextField();
        Input15 = new javax.swing.JTextField();
        Input16 = new javax.swing.JTextField();
        Input17 = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Harga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Harga.setText("Harga Barang");

        Banyak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Banyak.setText("Banyaknya");

        Diskon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Diskon.setText("Harga Barang Diskon");

        Total.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Total.setText("Total");

        Judul.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Judul.setText("Mini Kasir");

        Input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input1ActionPerformed(evt);
            }
        });

        Input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input2ActionPerformed(evt);
            }
        });

        Input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input3ActionPerformed(evt);
            }
        });

        Input4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input4ActionPerformed(evt);
            }
        });

        Input5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input5ActionPerformed(evt);
            }
        });

        Input6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input6ActionPerformed(evt);
            }
        });

        Input7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input7ActionPerformed(evt);
            }
        });

        Input8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input8ActionPerformed(evt);
            }
        });

        Input9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input9ActionPerformed(evt);
            }
        });

        Input10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input10ActionPerformed(evt);
            }
        });

        Input11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input11ActionPerformed(evt);
            }
        });

        Input12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input12ActionPerformed(evt);
            }
        });

        Harga1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Harga1.setText("Barang 1");

        Harga2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Harga2.setText("Barang 2");

        Harga3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Harga3.setText("Barang 3");

        Diskon1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Diskon1.setText("Diskon 10% jika lebih dari 100 barang");

        Diskon2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Diskon2.setText("Total Pembayaran");

        Diskon3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Diskon3.setText("Diskon 5% jika pembelian diatas 1.000.000");

        Diskon4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Diskon4.setText("Total setelah diskon");

        Diskon5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Diskon5.setText("Bayar");

        Diskon6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Diskon6.setText("Baya Uang kembali");

        Input13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input13ActionPerformed(evt);
            }
        });

        Input14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input14ActionPerformed(evt);
            }
        });

        Input15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input15ActionPerformed(evt);
            }
        });

        Input16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input16ActionPerformed(evt);
            }
        });

        Input17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input17ActionPerformed(evt);
            }
        });

        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus Semua");

        exit.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(Harga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Total)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Harga2)
                    .addComponent(Harga1)
                    .addComponent(Harga3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Input1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Input5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Input6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Input9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Input4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Input8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Input7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Input10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Banyak)
                        .addGap(69, 69, 69)
                        .addComponent(Diskon)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Judul)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Diskon1)
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Diskon3)
                            .addComponent(Diskon2)
                            .addComponent(Diskon4)
                            .addComponent(Diskon5)
                            .addComponent(Diskon6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Input13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Input14, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Input15, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Input16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Input17, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total)))
                            .addComponent(jButton2))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hapus)
                    .addComponent(exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Judul)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Banyak)
                    .addComponent(Harga)
                    .addComponent(Diskon)
                    .addComponent(Total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Input1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Input2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Input3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Harga2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)
                            .addComponent(Harga3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Harga1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Diskon1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Input13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Diskon2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Input14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Diskon3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Input15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Diskon4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Input16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Diskon5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Input17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Diskon6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input1ActionPerformed

    private void Input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input2ActionPerformed

    private void Input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input3ActionPerformed

    private void Input4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input4ActionPerformed

    private void Input5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input5ActionPerformed

    private void Input6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input6ActionPerformed

    private void Input7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input7ActionPerformed

    private void Input8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input8ActionPerformed

    private void Input9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input9ActionPerformed

    private void Input10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input10ActionPerformed

    private void Input11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input11ActionPerformed

    private void Input12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input12ActionPerformed

    private void Input13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input13ActionPerformed

    private void Input14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input14ActionPerformed

    private void Input15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input15ActionPerformed

    private void Input16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input16ActionPerformed

    private void Input17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input17ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
       Input1.setText(Input1.getText());
       Input2.setText(Input2.getText());
       Input3.setText(Input3.getText());
       Input4.setText(Input4.getText());
       Input5.setText(Input5.getText());
       Input6.setText(Input6.getText());
       Input7.setText(Input7.getText());
       Input8.setText(Input8.getText());
       Input9.setText(Input9.getText());
       Input10.setText(Input10.getText());
       Input11.setText(Input11.getText());
       Input12.setText(Input12.getText());
       Input13.setText(Input13.getText());
       Input14.setText(Input14.getText());
       Input15.setText(Input15.getText());
       Input16.setText(Input16.getText());
       Input17.setText(Input17.getText());
        double jumlah,hasil;
        double des = 0; 
       int a,b;
       
       a = Integer.valueOf(Input1.getText());
       b = Integer.valueOf(Input4.getText());
       
       jumlah = a * b;
      
       if( b  > 100)
       {
          hasil =(a - (a * 10)/100);
          Input7.setText(""+hasil);
          Input10.setText(""+ (jumlah - ((jumlah * 10)/100)));
       }
       else{
           Input10.setText(""+jumlah);
           Input7.setText(""+des);
       }
       
       
       double jumlah1,hasil1,c1;
       int a1,b1;
       
       a1 = Integer.valueOf(Input2.getText());
       b1 = Integer.valueOf(Input5.getText());
       
       jumlah1 = a1 * b1;
       c1 = (jumlah1 - ((jumlah1 * 10)/100));
               
       if(b1 > 100){
           hasil1 = (a1 - (a1 * 10)/100);
           Input8.setText(""+hasil1);
           Input11.setText(""+ c1);
       }
       else{
           Input11.setText(""+jumlah1);
           Input8.setText(""+des);
       }
       
       double jumlah2,hasil2,c2;
       int a2,b2;
       
       a2 = Integer.valueOf(Input3.getText());
       b2 = Integer.valueOf(Input6.getText());
       
       jumlah2 = a2 * b2;
       c2 = (jumlah2 - ((jumlah2 * 10)/100));
       if(b2 > 100){
           hasil2 =(a2 - (a2 * 10) /100);
           Input9.setText(""+hasil2);
           Input12.setText(""+ c2);
       }
       else{
           Input12.setText(""+jumlah2);
           Input9.setText(""+des);
       }
       double Pembayaran,hasil4,c5;
       
       Pembayaran =  jumlah + c1 + jumlah2;
       Input13.setText(""+Pembayaran);
       hasil4 = (Pembayaran - (Pembayaran * 5)/100);
       if(Pembayaran > 1000000){
           c5 = (Pembayaran * 5)/100;
           Input14.setText(""+c5);
           Input15.setText(""+hasil4);
       }else{
           Input15.setText(""+Pembayaran);
       }
    }//GEN-LAST:event_totalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double c7,c8;
       
       c7 = Integer.parseInt(Input16.getText());
       c8 = c7 - Input;
       Input17.setText(""+c8);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line guments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Banyak;
    public javax.swing.JLabel Diskon;
    public javax.swing.JLabel Diskon1;
    public javax.swing.JLabel Diskon2;
    public javax.swing.JLabel Diskon3;
    public javax.swing.JLabel Diskon4;
    public javax.swing.JLabel Diskon5;
    public javax.swing.JLabel Diskon6;
    public javax.swing.JButton Hapus;
    public javax.swing.JLabel Harga;
    public javax.swing.JLabel Harga1;
    public javax.swing.JLabel Harga2;
    public javax.swing.JLabel Harga3;
    public javax.swing.JTextField Input1;
    public javax.swing.JTextField Input10;
    public javax.swing.JTextField Input11;
    public javax.swing.JTextField Input12;
    public javax.swing.JTextField Input13;
    public javax.swing.JTextField Input14;
    public javax.swing.JTextField Input15;
    public javax.swing.JTextField Input16;
    public javax.swing.JTextField Input17;
    public javax.swing.JTextField Input2;
    public javax.swing.JTextField Input3;
    public javax.swing.JTextField Input4;
    public javax.swing.JTextField Input5;
    public javax.swing.JTextField Input6;
    public javax.swing.JTextField Input7;
    public javax.swing.JTextField Input8;
    public javax.swing.JTextField Input9;
    public javax.swing.JLabel Judul;
    public javax.swing.JLabel Total;
    public javax.swing.JButton exit;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
